title: 不问归期
description: 我的个人博客
author: Freagle
logo: /static/img/avatar.png
github: https://github.com/fzp-cxsys
about: 生活不至于眼前的苟且，还有诗和远方。

baseurl: ""
url: "https://codeasashu.github.io/hcz-jekyll-blog"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
